name: Docker

# on:
#   push:
#     branches: [ main ]

# env:
#   DOCKER_IMAGE: DOCKER_IMAGE
#   VERSION: VERSION
#   NAME: cicd

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up docker buildx
#         uses: docker/setup-buildx-action@v1
#       - name: Cache docker layers
#         uses: actions/cache@v2
#       - name: Login to ghcr
#         uses: docker/login-action@v1
#       - name: Build and push
#         id: docker_build
#         uses: docker/build-push-action@v2

#   deploy:
#     needs: build
#     name: Deploy
#     steps:
#       - name: Login to ghcr
#         uses: docker/login-action@v1
#       - name: Docker run
#         run: |
#           docker run
#       - name: action-slack
#         uses: 8398a7/action-slack@v3
#         with:
#           status: ${{ job.status }}
#           author_name: Github Actions
#           fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
#         env:
#           SLACK_WEBHOOK_URL: SLACK_WEBHOOK_URL
#         if: always()